services:
  cockroach1:
    image: cockroachdb/cockroach:v23.1.11
    container_name: cockroach1
    command: start --insecure --join=cockroach1,cockroach2,cockroach3
    ports:
      - "8080:8080"   # UI Web
      - "26257:26257" # PostgreSQL port
    volumes:
      - cockroach1-data:/cockroach/cockroach-data
    networks:
      - cockroach-net

  cockroach2:
    image: cockroachdb/cockroach:v23.1.11
    container_name: cockroach2
    command: start --insecure --join=cockroach1,cockroach2,cockroach3
    networks:
      - cockroach-net
    volumes:
      - cockroach2-data:/cockroach/cockroach-data

  cockroach3:
    image: cockroachdb/cockroach:v23.1.11
    container_name: cockroach3
    command: start --insecure --join=cockroach1,cockroach2,cockroach3
    networks:
      - cockroach-net
    volumes:
      - cockroach3-data:/cockroach/cockroach-data

volumes:
  cockroach1-data:
  cockroach2-data:
  cockroach3-data:

networks:
  cockroach-net:
