data_directory = '/var/lib/postgresql/data'
hba_file = '/var/lib/postgresql/conf/pg_hba.conf'
listen_addresses = '*'
port = 5432
max_wal_senders = 10
wal_level = replica
wal_keep_size = 64
archive_mode = on
archive_command = 'cp %p /var/lib/postgresql/data/archive/%f'
